### ISSUE TITLE
Separate leaderboards for 1 switch vs 2 switches

### ISSUE THREAD

**Issue by keijak** [tarao/prisoners-switch#17]
Since algorithms for a single switch and those for two switches are very different, it makes little sense to order them following one particular ranking criterion.

I guess the current leaderboard will soon be occupied with solutions for the single-switch case since they tend to get higher score, however, one would find more diverse & creative solutions in the 2-switch case. Why not have separate leaderboards?

**Comment by tarao** [comment]
It is by design that a single-switch algorithm gets higher score than any other 2-switch algorithms.  There are many inefficient 2-switch strategies that require the second switch not only for optimization.  People who figured out such a strategy would feel that the single-switch problem is more difficult.  So they get more points when they win the second stage.  This is the scenario.

I know that not all people feel like this.  Especially for you guys, perhaps there was no difficulty to take a step toward the single-switch problem and the two problems looked just different settings of the same kind of problem.  But I think that is a point of view from experts.  I still prefer the system giving a two-staged experience to people.  Scores and ranks are provided for this purpose, or simply, just for fun.

I also appreciate that experts are seeking for more efficient strategies but I feel this like extra stages after the end credits of the game.  I still agree that it's going to be useful if there is a view for experts to compare the results.  So how about having it outside the existing leaderboards?

I made sheets to show the list of answers separately:
https://docs.google.com/spreadsheets/d/1qhZFYmxQyp2Z6GC2FmpmGmbKVggI83FLxMUtcw_hC9U/edit?usp=sharing

Does this help you?

**Comment by keijak** [comment]
Thanks for making separate sheets. It's more than enough for me!

The motivation here is that I want interesting 2-switch solutions to be more discoverable (and the same for probabilistic solutions if they were accepted), but it's too early to discuss this topic since only a few solutions are submitted at this point. All of them are still discoverable . You don't have to fix a problem that doesn't exist yet:-)
