### ISSUE TITLE
A non-strict rule for probabilistic algorithms

### ISSUE THREAD

**Issue by keijak** [tarao/prisoners-switch#18]
While I understand that strict algorithms that 100% win the game are the expected answers in this puzzle, I'm guessing that there are interesting probabilistic solutions that practically pass all fair games (but fail in an unfair game) and are much more efficient than the best strict algorithms. I'm interested in those as well.

I think [my first solution](https://github.com/tarao/prisoners-switch/pull/9) is a good example. Assuming the input is truly random (e.g. conforming uniform distribution), we could prove that, for an arbitrarily small epsilon > 0, an integer K exists with which the algorithm fails at a probability smaller than the epsilon. I think of several other examples like that.

How about making it another class of the game (like you did for a single switch use)? Maybe accept those solutions that pass all of fair games, but give them 0 score if they fail in the unfair game.

It will be even nicer if it comes with [a separate leaderboard](https://github.com/tarao/prisoners-switch/issues/17), for which I made another feature request.

**Comment by tarao** [comment]
I see.  I understand that probabilistic approaches are interesting.  However, I'm still not sure if it is possible to distinguish a cheating strategy from real probabilistic solutions automatically.

For example, think about a strategy which counts the number of prisoners entering the room in a global variable and makes assertions in all games when the number reaches to `(num of games) * (num of prisoners) - 1 * (num of unfair games)`.  Maybe we can decide the number of prisoners that do not enter the room in unfair games randomly, but I think there can be a probabilistic solution which is accelerated by cheating.

If it requires a human review anyway, isn't it enough to give some place (maybe an issue on this repository) where people bring their probabilistic implementations and discuss their efficiency?  It would still be better to modify the (command line) verifier to report the steps of fair games and not to stop until a fair game fails or all fair games pass, so that it helps the discussion.

Unless probabilistic solutions are testable by machines, I prefer the automated checker on the CI to reject probabilistic strategies.  I can fix the command line verifier for them to be meaningfully reported.  Is this enough for you?

**Comment by keijak** [comment]
Thanks for your thoughts. Now I see why mortal games were introduced. I don't think of a cheap way to prevent cheating through global variables, either.

So, I agree with you for now. The fix in command line tool you suggested will be very helpful to explore probabilistic solutions. When someone comes up with a better protection against cheating, we might revisit this. Thanks!

**Comment by tarao** [comment]
Now we have "patient" mode not to exit on detecting the first failure: cd054bfd029eb2e6a0e0718fcfe17b5ff4a46072

On command line,

```
verifier/run -patient
```

will successfully finish if all fair games pass.

**Comment by keijak** [comment]
Awesome. I gave it a try today and it's working as I expect. Thanks for implementing the mode!
